ALTER TABLE customer
  MODIFY first_name VARCHAR(255) NULL,
  MODIFY last_name VARCHAR(255) NULL,
  MODIFY full_name VARCHAR(255) NULL,
  MODIFY company VARCHAR(255) NULL,
  MODIFY email VARCHAR(255) NULL,
  MODIFY phone VARCHAR(255) NULL,
  MODIFY address_line1 VARCHAR(255) NULL,
  MODIFY address_line2 VARCHAR(255) NULL,
  MODIFY postal_code VARCHAR(255) NULL,
  MODIFY city VARCHAR(255) NULL;
