import type { Express } from "express";
import type { Server } from "http";
import { enforceAdminMaintenancePolicy } from "./middleware/adminMaintenancePolicy";
import { resolveUserRole } from "./middleware/resolveUserRole";
import { requireSessionUser, sessionAuth } from "./middleware/sessionAuth";
import { setupGate } from "./middleware/setupGate";
import backupRoutes from "./routes/backupRoutes";
import customerNotesRoutes from "./routes/customerNotesRoutes";
import customerAttachmentsRoutes from "./routes/customerAttachmentsRoutes";
import customersRoutes from "./routes/customersRoutes";
import employeeAttachmentsRoutes from "./routes/employeeAttachmentsRoutes";
import employeeNotesRoutes from "./routes/employeeNotesRoutes";
import employeesRoutes from "./routes/employeesRoutes";
import helpTextsRoutes from "./routes/helpTextsRoutes";
import masterDataRoutes from "./routes/masterDataRoutes";
import noteTemplatesRoutes from "./routes/noteTemplatesRoutes";
import notesRoutes from "./routes/notesRoutes";
import appointmentsRoutes from "./routes/appointmentsRoutes";
import appointmentAttachmentsRoutes from "./routes/appointmentAttachmentsRoutes";
import appointmentNotesRoutes from "./routes/appointmentNotesRoutes";
import documentExtractionRoutes from "./routes/documentExtractionRoutes";
import projectAttachmentsRoutes from "./routes/projectAttachmentsRoutes";
import projectNotesRoutes from "./routes/projectNotesRoutes";
import projectsRoutes from "./routes/projectsRoutes";
import reportConfigsRoutes from "./routes/reportConfigsRoutes";
import reportsRoutes from "./routes/reportsRoutes";
import monitoringRoutes from "./routes/monitoringRoutes";
import dataVersionRoutes from "./routes/dataVersionRoutes";
import teamEmployeesRoutes from "./routes/teamEmployeesRoutes";
import teamsRoutes from "./routes/teamsRoutes";
import tagsRoutes from "./routes/tagsRoutes";
import tourEmployeesRoutes from "./routes/tourEmployeesRoutes";
import tourWeeksRoutes from "./routes/tourWeeksRoutes";
import tourWeekEmployeesRoutes from "./routes/tourWeekEmployeesRoutes";
import toursRoutes from "./routes/toursRoutes";
import userSettingsRoutes from "./routes/userSettingsRoutes";
import usersRoutes from "./routes/usersRoutes";
import authRoutes from "./routes/authRoutes";
import attachmentQueriesRoutes from "./routes/attachmentQueriesRoutes";
import calendarWeekNotesRoutes from "./routes/calendarWeekNotesRoutes";
import calendarMarkersRoutes from "./routes/calendarMarkersRoutes";
import changeNotificationsRoutes from "./routes/changeNotificationsRoutes";
import systemSeedRoutes from "./routes/systemSeedRoutes";
import journalRoutes from "./routes/journalRoutes";
import correctionWorkflowRoutes from "./routes/correctionWorkflowRoutes";

export async function registerRoutes(httpServer: Server, app: Express): Promise<Server> {
  app.use("/api", (_req, res, next) => {
    res.setHeader("Cache-Control", "no-store");
    next();
  });

  app.use("/api", sessionAuth);
  app.use("/api", setupGate);
  app.use(authRoutes);

  app.use("/api", requireSessionUser);
  app.use("/api", resolveUserRole);
  app.use("/api", enforceAdminMaintenancePolicy);

  app.use(backupRoutes);
  app.use(appointmentsRoutes);
  app.use(appointmentAttachmentsRoutes);
  app.use(appointmentNotesRoutes);
  app.use(documentExtractionRoutes);
  app.use(toursRoutes);
  app.use(teamsRoutes);
  app.use(tagsRoutes);
  app.use(customersRoutes);
  app.use(customerNotesRoutes);
  app.use(customerAttachmentsRoutes);
  app.use(notesRoutes);
  app.use(noteTemplatesRoutes);
  app.use(helpTextsRoutes);
  app.use(masterDataRoutes);
  app.use(employeeNotesRoutes);
  app.use(employeesRoutes);
  app.use(employeeAttachmentsRoutes);
  app.use(tourEmployeesRoutes);
  app.use(tourWeeksRoutes);
  app.use(tourWeekEmployeesRoutes);
  app.use(teamEmployeesRoutes);
  app.use(projectsRoutes);
  app.use(reportConfigsRoutes);
  app.use(reportsRoutes);
  app.use(monitoringRoutes);
  app.use(dataVersionRoutes);
  app.use(changeNotificationsRoutes);
  app.use(projectNotesRoutes);
  app.use(projectAttachmentsRoutes);
  app.use(calendarMarkersRoutes);
  app.use(calendarWeekNotesRoutes);
  app.use(journalRoutes);
  app.use(attachmentQueriesRoutes);
  app.use(correctionWorkflowRoutes);
  app.use(systemSeedRoutes);
  app.use(userSettingsRoutes);
  app.use(usersRoutes);

  return httpServer;
}
