import type {
  DatabaseCanaryProfile,
  StorageCanaryProfile,
} from "./testIsolationCanaries";
import type {
  TestIsolationBaseline,
  TestIsolationClass,
  TestIsolationResetScope,
  TestIsolationStorageProfile,
} from "./testIsolationExecution";
import { normalizeTestPath } from "./testIsolationExecution";

export type TestIsolationRegistryEntry = {
  suitePath: string;
  isolationClass: TestIsolationClass;
  baseline: TestIsolationBaseline;
  storageProfile: TestIsolationStorageProfile;
  resetScope: TestIsolationResetScope;
  canaryProfile: DatabaseCanaryProfile | StorageCanaryProfile;
  pilotStatus: "validated" | "validated-with-hard-isolation";
  rolloutMode: "candidate-default" | "pilot-only";
  notes: string;
};

const isolationRegistry: TestIsolationRegistryEntry[] = [
  {
    suitePath: "tests/integration/server/projects.paged-list.integration.test.ts",
    isolationClass: "B",
    baseline: "core",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Erste kontrollierte default-Rollout-Suite nach stabilem per-suite Canary-Pilot.",
  },
  {
    suitePath: "tests/integration/server/customers.paged-list.integration.test.ts",
    isolationClass: "B",
    baseline: "core",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Paginierte Kundenliste ist nach Token-Haertung stabil im per-suite Canary-Pilot.",
  },
  {
    suitePath: "tests/integration/server/appointments.list.sorting.integration.test.ts",
    isolationClass: "B",
    baseline: "core",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Terminlisten-Sortierung bleibt im per-suite Kandidatenmodell inklusive OrderNumber-Canary stabil.",
  },
  {
    suitePath: "tests/integration/server/projects.scope.mengenlogik.integration.test.ts",
    isolationClass: "B",
    baseline: "core",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Projekt-Scope-Mengenlogik bleibt im per-suite Canary-Pilot fuer all/withAppointments/upcoming/noAppointments stabil.",
  },
  {
    suitePath: "tests/integration/server/entity-appointments-preview.endpoint.integration.test.ts",
    isolationClass: "B",
    baseline: "core",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Entity-Appointment-Preview bleibt im per-suite Kandidatenmodell ueber Customer-, Employee- und Project-Scope stabil.",
  },
  {
    suitePath: "tests/integration/server/appointments.direct-projections.integration.test.ts",
    isolationClass: "B",
    baseline: "core",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Direkttermin-Projektionen bleiben im per-suite Canary-Pilot fuer Listen-, Kalender- und Delete-Pfade stabil.",
  },
  {
    suitePath: "tests/integration/server/reports.auftragsliste.integration.test.ts",
    isolationClass: "B",
    baseline: "core",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Auftragsliste bleibt im per-suite Canary-Pilot fuer Kategorienfilter, Reklamationsausschluss und Storno-Fallback stabil.",
  },
  {
    suitePath: "tests/integration/server/reports.vorlaufliste.integration.test.ts",
    isolationClass: "B",
    baseline: "core",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Vorlaufliste bleibt nach Idempotenz-Haertung fuer wiederholte Artikel- und Rollenfixtures im per-suite Canary-Pilot stabil.",
  },
  {
    suitePath: "tests/integration/server/reports.vorlaufliste.printPreview.integration.test.ts",
    isolationClass: "B",
    baseline: "core",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Vorlaufliste-Druckvorschau bleibt im per-suite Canary-Pilot fuer Vollmenge und Listenparitaet stabil.",
  },
  {
    suitePath: "tests/integration/server/appointments.tour-change-preview.integration.test.ts",
    isolationClass: "B",
    baseline: "core",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Tour-Change-Preview bleibt im per-suite Canary-Pilot fuer KW-Wechsel und spaetere Tourzuordnung stabil.",
  },
  {
    suitePath: "tests/integration/server/masterData.visibility.by-role.test.ts",
    isolationClass: "B",
    baseline: "core",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Masterdata-Sichtbarkeit bleibt im per-suite Canary-Pilot fuer Rollenfilter und Aktiv-Defaults stabil.",
  },
  {
    suitePath: "tests/integration/server/customers.visibility.by-role.test.ts",
    isolationClass: "B",
    baseline: "core",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Kunden-Sichtbarkeit bleibt nach monotone Credentials- und Kundennummern-Haertung im per-suite Canary-Pilot stabil.",
  },
  {
    suitePath: "tests/integration/server/employees.visibility.by-role.test.ts",
    isolationClass: "B",
    baseline: "core",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Mitarbeiter-Sichtbarkeit bleibt nach monotone Credentials-Haertung im per-suite Canary-Pilot stabil.",
  },
  {
    suitePath: "tests/integration/server/appointments.park.integration.test.ts",
    isolationClass: "A",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-test",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated-with-hard-isolation",
    rolloutMode: "pilot-only",
    notes: "Park-Integration braucht reservierte System-Tags und Parkplatz-Tour; bleibt deshalb auf harter seeded Isolation.",
  },
  {
    suitePath: "tests/integration/server/attachments.delete.ft19.integration.test.ts",
    isolationClass: "S",
    baseline: "core",
    storageProfile: "uploads",
    resetScope: "per-test",
    canaryProfile: "attachment-confusion",
    pilotStatus: "validated-with-hard-isolation",
    rolloutMode: "pilot-only",
    notes: "Attachment-Loeschworkflow schreibt in Upload-Storage und braucht harte Storage-Isolation pro Test.",
  },
  {
    suitePath: "tests/integration/server/appointments.attachments.integration.test.ts",
    isolationClass: "S",
    baseline: "core",
    storageProfile: "uploads",
    resetScope: "per-test",
    canaryProfile: "attachment-confusion",
    pilotStatus: "validated-with-hard-isolation",
    rolloutMode: "pilot-only",
    notes: "Storage-Sonderfall bleibt vorerst auf harter Isolation.",
  },
  {
    suitePath: "tests/integration/server/admin.system-seed.integration.test.ts",
    isolationClass: "S",
    baseline: "core",
    storageProfile: "none",
    resetScope: "per-test",
    canaryProfile: "seed-shadow",
    pilotStatus: "validated-with-hard-isolation",
    rolloutMode: "pilot-only",
    notes: "Seed-Suite zeigt echte Cross-Test-Pollution und bleibt per-test.",
  },
  {
    suitePath: "tests/integration/server/tourWeekEmployees.integration.test.ts",
    isolationClass: "A",
    baseline: "core",
    storageProfile: "none",
    resetScope: "per-test",
    canaryProfile: "week-plan-confusion",
    pilotStatus: "validated-with-hard-isolation",
    rolloutMode: "pilot-only",
    notes: "Mehrschrittige Wochenplanung bleibt Klasse A.",
  },
  {
    suitePath: "tests/e2e-browser/appointments-list.filter-scope.browser.e2e.spec.ts",
    isolationClass: "B",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Erste kontrollierte Browser-default-Suite nach stabilem per-suite Canary-Pilot.",
  },
  {
    suitePath: "tests/e2e-browser/projects.filter-scopes.browser.e2e.spec.ts",
    isolationClass: "B",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Projekt-Scope-Browser-Suite ist stabil im seeded per-suite Canary-Pilot.",
  },
  {
    suitePath: "tests/e2e-browser/appointments-list.period-picker.browser.e2e.spec.ts",
    isolationClass: "B",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Period-Picker-Browser-Suite nutzt den echten Suite-Pfad im Reset und bleibt im seeded Canary-Pilot stabil.",
  },
  {
    suitePath: "tests/e2e-browser/settingsPage.navigation.browser.e2e.spec.ts",
    isolationClass: "B",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Settings-Navigation nutzt den echten Suite-Pfad im Reset; Canary-Lauf bleibt ohne relevante Angriffsfläche stabil.",
  },
  {
    suitePath: "tests/e2e-browser/settingsPage.controls.browser.e2e.spec.ts",
    isolationClass: "B",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Settings-Steuerelemente persistieren im seeded per-suite Kandidatenmodell stabil; Canary-Lauf bleibt ohne relevante Listenangriffsfläche gruen.",
  },
  {
    suitePath: "tests/e2e-browser/calendar-markers-visualization.browser.e2e.spec.ts",
    isolationClass: "B",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Kalendermarker-Browser-Suite nutzt gespeicherte Marker, globale Settings und Kalenderanzeige ohne eigene harte Reset-Pfade.",
  },
  {
    suitePath: "tests/e2e-browser/filter-state-persistence.browser.e2e.spec.ts",
    isolationClass: "B",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Filter-State-Persistenz bleibt im seeded per-suite Canary-Pilot ueber Projekte, Kunden, Termine und Mitarbeiter stabil.",
  },
  {
    suitePath: "tests/e2e-browser/reports.open-modes.browser.e2e.spec.ts",
    isolationClass: "B",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Report-Open-Modes nutzen den echten Suite-Pfad im Reset und bleiben fuer Inline- plus Standalone-Reports im seeded Canary-Pilot stabil.",
  },
  {
    suitePath: "tests/e2e-browser/standalone-routing.browser.e2e.spec.ts",
    isolationClass: "B",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Standalone-Routing nutzt den echten Suite-Pfad im Reset und bleibt fuer Navigation, Popup-Flows und Edit-Rueckwege im seeded Canary-Pilot stabil.",
  },
  {
    suitePath: "tests/e2e-browser/appointments-list.tour-employee.browser.e2e.spec.ts",
    isolationClass: "B",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Tour-/Mitarbeiter-Terminliste nutzt den echten Suite-Pfad im Reset und bleibt fuer Sortierung, Scope-Toggles und Tabellenlayout im seeded Canary-Pilot stabil.",
  },
  {
    suitePath: "tests/e2e-browser/appointment-cancellation.workflow.browser.e2e.spec.ts",
    isolationClass: "A",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "pilot-only",
    notes: "Storno-Workflow braucht reservierte System-Tags und bleibt als fachlich dichter Browser-Sonderfall konservativ.",
  },
  {
    suitePath: "tests/e2e-browser/appointment-form.create-sidebar-persistence.browser.e2e.spec.ts",
    isolationClass: "A",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "pilot-only",
    notes: "Create-Sidebar-Flow mit Tour-Messe- und Anmerkungen-Regeln bleibt als seed-abhaengiger Browser-Sonderfall konservativ.",
  },
  {
    suitePath: "tests/e2e-browser/appointment-form.layout-tour-integration.browser.e2e.spec.ts",
    isolationClass: "A",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "week-plan-confusion",
    pilotStatus: "validated-with-hard-isolation",
    rolloutMode: "pilot-only",
    notes: "Tour-Integration mit Wochenplanung und Tour-Messe-Regeln bleibt als komplexer Browser-Sonderfall konservativ.",
  },
  {
    suitePath: "tests/e2e-browser/appointment-park.workflow.browser.e2e.spec.ts",
    isolationClass: "A",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "pilot-only",
    notes: "Park-Workflow braucht reservierte System-Tags plus Parkplatz-Tour und bleibt vorerst pilot-only.",
  },
  {
    suitePath: "tests/e2e-browser/ft33-absence-readonly.browser.e2e.spec.ts",
    isolationClass: "A",
    baseline: "core",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "pilot-only",
    notes: "FT33 Readonly-Schnitt startet vom Core-Reset und zieht den benoetigten System-Seed explizit nach, um regulaere sowie dedizierte Abwesenheits-Mutationspfade ueber mehrere Oberflaechen zu pruefen.",
  },
  {
    suitePath: "tests/e2e-browser/ft33-absence-week-planning.browser.e2e.spec.ts",
    isolationClass: "A",
    baseline: "core",
    storageProfile: "none",
    resetScope: "per-test",
    canaryProfile: "week-plan-confusion",
    pilotStatus: "validated-with-hard-isolation",
    rolloutMode: "pilot-only",
    notes: "FT33-KW-Planungsabzug nutzt echte Termin- und Tour-KW-Daten pro Test und zieht den System-Seed explizit nach.",
  },
  {
    suitePath: "tests/e2e-browser/calendar-month-sheet.navigation.browser.e2e.spec.ts",
    isolationClass: "B",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Monatsuebersicht nutzt den echten Suite-Pfad im Reset und bleibt fuer Einzelblatt-Navigation im seeded Canary-Pilot stabil.",
  },
  {
    suitePath: "tests/e2e-browser/reports.ft26.browser.e2e.spec.ts",
    isolationClass: "B",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "FT26-Reports nutzen den echten Suite-Pfad im Reset und bleiben fuer Vorlaufliste, Druckvorschau und Produktionsplanung im seeded Canary-Pilot stabil.",
  },
  {
    suitePath: "tests/e2e-browser/reports.tourenplan.browser.e2e.spec.ts",
    isolationClass: "B",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Tourenplan-Report nutzt den echten Suite-Pfad im Reset und bleibt fuer Vorschau- und Print-Paritaet im seeded Canary-Pilot stabil.",
  },
  {
    suitePath: "tests/e2e-browser/refresh-button.browser.e2e.spec.ts",
    isolationClass: "B",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Refresh-Button nutzt den echten Suite-Pfad im Reset und bleibt fuer Haupt- plus Standalone-Views im seeded Canary-Pilot stabil.",
  },
  {
    suitePath: "tests/e2e-browser/tag-selection-unification.browser.e2e.spec.ts",
    isolationClass: "B",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "candidate-default",
    notes: "Tag-Auswahl nutzt den echten Suite-Pfad im Reset und bleibt fuer Picker, Filter und Wochenkarten im seeded Canary-Pilot stabil.",
  },
  {
    suitePath: "tests/e2e-browser/settingsPage.backup.browser.e2e.spec.ts",
    isolationClass: "S",
    baseline: "seeded",
    storageProfile: "backups",
    resetScope: "per-suite",
    canaryProfile: "backup-confusion",
    pilotStatus: "validated",
    rolloutMode: "pilot-only",
    notes: "Backup-Sonderfall bleibt bis zu weiteren Piloten konservativ.",
  },
  {
    suitePath: "tests/e2e-browser/admin-sauna-project-title-migration.browser.e2e.spec.ts",
    isolationClass: "B",
    baseline: "core",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "pilot-only",
    notes: "Admin-Migration nutzt echte Projekt- und Artikeldaten, schreibt Workflow-Artefakte aber in isolierten Temp-Storage.",
  },
  {
    suitePath: "tests/e2e-browser/users-management-scroll.browser.e2e.spec.ts",
    isolationClass: "B",
    baseline: "core",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "pilot-only",
    notes: "Benutzerlisten-Scrolltest nutzt echte synthetische Userdaten und keine Storage-Artefakte.",
  },
  {
    suitePath: "tests/e2e-browser/project-form.create-sidebar-persistence.browser.e2e.spec.ts",
    isolationClass: "A",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "pilot-only",
    notes: "Projekt-Create-Sidebar mit Anmerkungen-Regel und Extraktionspfad bleibt als seed-abhaengiger Browser-Sonderfall konservativ.",
  },
  {
    suitePath: "tests/e2e-browser/tour-week-form.browser.e2e.spec.ts",
    isolationClass: "A",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-test",
    canaryProfile: "week-plan-confusion",
    pilotStatus: "validated-with-hard-isolation",
    rolloutMode: "pilot-only",
    notes: "Komplexer Wochenplan-UI-Flow bleibt auf harter Isolation.",
  },
  {
    suitePath: "tests/e2e-browser/tag-rule-engine.workflow.browser.e2e.spec.ts",
    isolationClass: "A",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "project-list-confusion",
    pilotStatus: "validated",
    rolloutMode: "pilot-only",
    notes: "Tag-Rule-Engine braucht verwaltete System-Tags und Notizvorlagen und bleibt deshalb seed-abhaengig pilot-only.",
  },
  {
    suitePath: "tests/e2e-browser/appointment-mutation-dialogs.browser.e2e.spec.ts",
    isolationClass: "B",
    baseline: "seeded",
    storageProfile: "none",
    resetScope: "per-suite",
    canaryProfile: "week-plan-confusion",
    pilotStatus: "candidate",
    rolloutMode: "pilot-only",
    notes: "Prueft Dialog-Verhalten nach Terminmutationen (MILE-53). Seed-abhaengig wegen Tour- und Wochenplan-Fixtures.",
  },
];

export function listRegisteredIsolationSuites(): TestIsolationRegistryEntry[] {
  return isolationRegistry;
}

export function getRegisteredIsolationSuite(testPath: string | null | undefined): TestIsolationRegistryEntry | null {
  const normalizedPath = normalizeTestPath(testPath);
  if (!normalizedPath) {
    return null;
  }

  return isolationRegistry.find((entry) => {
    const suitePath = normalizeTestPath(entry.suitePath);
    return normalizedPath === suitePath || normalizedPath.endsWith(`/${suitePath}`);
  }) ?? null;
}
